customhost = "employee.cjy3t7nhdh6e.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat"
customdb = "employee"
custombucket = "employeeadddata"
customregion = "ap-south-1"
